---
title: "Instrumental Phonetics 2018"
---

[Here](https://www.hse.ru/data/2018/01/26/1162932180/program-1719609140-3tWrq6PIZD.pdf) is a link to a course programme.

Final Mark =0.6 $\times$ (HW) + 0.4 $\times$ (Exam)

### 1. Introduction to Acoustic Phonetics
* (03.02.2017)	[Lec 1](https://goo.gl/RSz84p)
* (03.02.2017)	Lab 1: [Praat](http://www.fon.hum.uva.nl/praat/). Symbols for [consonats](http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__consonants_1.png), [vowels](http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__vowels_1.png) and [diacritics](http://www.fon.hum.uva.nl/praat/manual/Phonetic_symbols__diacritics.html)
* HW 1 (due to 10.02.2018): 
      * Create the  annotation for [this sound file](https://github.com/agricolamz/2018_m_Instrumental_Phonetics/blob/master/docs/materials/andi_plosives.wav?raw=true) containing words *bek':ub* (hot), *wuk:udu* (fall down), *tʃ'ek'a* (foot) and *t'uka* (goat). Here is [an example](https://raw.githubusercontent.com/agricolamz/2018_m_Instrumental_Phonetics/master/docs/hw1.png).
      * Send the `.TextGrid` file to the course assistant [Aygul Zakirova](mailto:atgz@mail.ru) with topic `Instrumental Phonetics: HW 1`

### 2. Vowels. Formants
* (10.02.2017)	[Lec 2]()
* (10.02.2017)	[Lab 2]()
* [sound](https://goo.gl/IzpUyo)
* [TextGrid](https://goo.gl/4tGthZ)
* [extracted formant values](https://goo.gl/zPm7Od)
* [Lennes M. (2002) Calculate segment durations](http://www.helsinki.fi/%7Elennes/praat-scripts/public/calculate_segment_durations.praat)
* [Kawahara (??) Extract formant chart](https://goo.gl/MUBpPw)
* [R script for formant visualisation](https://goo.gl/8weIeL)

### 3. Sonorants
* ()	[Lec 3]()
* ()	[Lab 3]()
* [Andi nasals](https://goo.gl/5D9DNR)

### 4. Obstruents
* ()	[Lec 4]()
* ()	[Lab 4]()
* [fricatives](https://goo.gl/hvdviI), [fricatives' TextGrid](https://goo.gl/pza6tx), Extracted data: [ɬ](https://goo.gl/wo3QZN), [s](https://goo.gl/eNZQKa), [sh](https://goo.gl/NgeVSX), [x](https://goo.gl/oDYvbJ), [χ](https://goo.gl/vZQfZG) 
* [fricatives' R script](https://goo.gl/SdGlZr)
* [plosives](https://goo.gl/PZA8WY), [plosives' TextGrid](https://goo.gl/1ZFtJt), Extracted data: [plosives' duration](https://goo.gl/NExChs)
* [plosives' R script](https://goo.gl/g3oPfN)

### 5. Guess the word 
* ()	[Lab 5]()

### 6. Final Exam
* () [Tasks]()
  
Reference:

* Ashby, M., J. Maidment (2005). Introducing phonetic science. Cambridge University Press.
* Bickford, A. C., R. Floyd (2006). Articulatory Phonetics: Tools for Analyzing the World’s Languages SIL International. 
* Boersma,  P.,  D.  Weenink  (2013). Praat:    doing  phonetics  by  computer  (version 5.3.51)[computer program]. retrieved 2 june 2013.
* Fant, G. (1971). Acoustic theory of speech production:  with calculations based on X-ray studies of Russian articulations, Volume 2.  Walter de Gruyter.
* Fuchs, S., M. Toda„ M. Żygis (2010). Turbulent sounds:  an interdisciplinary guide, Volume 21.  Walter de Gruyter.
* Fulop, S. (2011). Speech spectrum analysis.  Springer Science & Business Media.
* Gick, B., I. Wilson D. Derrick (2012). Articulatory phonetics. John Wiley & Sons.
* Gordon, M., P. Ladefoged (2001).  Phonation types: a cross-linguistic overview. Journal of Phonetics 29 (4), 383–406.
* Harrington, J. (2010). Phonetic analysis of speech corpora. John Wiley & Sons.
* [Hon Hunt, E. (2009). Acoustic Characterization of the Glides /j/ and /w/ in American English](https://dspace.mit.edu/bitstream/handle/1721.1/52797/547382338-MIT.pdf;sequence=2)
* Johnson, K. (2011). Acoustic and auditory phonetics. John Wiley & Sons.
* Ladefoged, P., S. F. Disner (2012). Vowels and consonants. John Wiley & Sons.
Ladefoged, P., I. Maddieson. (1996). The Sounds of the World’s Languages Oxford, Cambridge: Blackwell Publishers.
* Rorabaugh, C. B. (2010). Notes on Digital Signal Processing: Practical Recipes for Design, Analysis and Implementation Prentice Hall